# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64
    # Runs a set of commands using the runners shell
    - name: Setup up virtualenv
      run : |
        python3 -m pip install setuptools
        python3 -m pip install virtualenv
        python3 -m pip install pip-tools
        python3 -m virtualenv .venv
        source .venv/bin/activate
    - name: Install test-requirements.
      run: |
        pip-compile test-requirements.in --output-file=test-requirements.txt
        pip-compile requirements.in --output-file=requirements.txt
        python3 -m pip install -r "test-requirements.txt"
        python3 -m pip install -r "requirements.txt"
    - name: Test
      run: pytest tests/ -v --black --cov-report=xml --cov=srv/ --pylint
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        fail_ci_if_error: true
